### ISSUE TITLE
Famland打造的是元宇宙精神商品的价值

### ISSUE THREAD

**Issue by mjy368837** [famland/website#73]
Famland元宇宙是一个100%完全社区化的项目，项目所涉及的开发、运营、市场经费全部来自普通用户投资或捐助， 项目发行的所有资产和收益，100%全部回馈社区玩家。

**Comment by linshande** [comment]
The Famland Metaverse is an NFT value-growing Play to Earn game ecosystem that integrates NFT, Game, and Defi. Any player only needs an EOS wallet address to create a Famland NFT, and players only need to pledge the meta-universe seed fund worth 100-500USDT in Famland to continuously obtain farming income YL, and continuously cultivate Famland's fertility and shared value by consuming YL, thereby obtaining higher returns.
The Famland of countless users is connected to form a new continent of value in the metaverse. This new continent, like the land on earth, can plant trees, build buildings, build shopping malls, build schools, and build factories on it, and can develop commerce, develop economy, develop culture, develop art, and build a new order and civilization for mankind.
The game is based on the original intention of people-oriented design, does not rely on capital investment, attaches importance to the value of players' time and wisdom investment in the game, and relies on the algorithm rules of NFT value cultivation and value sharing to maximize the protection of the basic rights and fairness of each player in the game, and minimize the unfavorable factors of using capital to damage the healthy development of the game ecology.
Famland Metacosmum is a fully community-based project, the project founding team has no pre-mining, no fee income, no operational commission, and all assets and proceeds issued by the project are 100% returned to the community players.
